# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/StatisticalFace',
                'doc_host': 'https://danaderp.github.io',
                'git_url': 'https://github.com/danaderp/StatisticalFace',
                'lib_path': 'StatisticalFace'},
  'syms': {'StatisticalFace.core': {'StatisticalFace.core.foo': ('core.html#foo', 'StatisticalFace/core.py')}}}
